apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: notaikr-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - not.ai.kr
  rules:
    - backendRefs:
        - name: notaikr-service
          port:
            number: 8080
