apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timeline
resources:
  - ./photon.yml
  - ./postgis.yml
  - ./rabbitmq.yml
  - ./redis.yml
  - ./reitti.yml
  - ./tilecache.yml
