apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - ./certificate.yml
  - ./clusterissuer.yml
  - ./nginx.yml
  - ./envoy.yml
  - ./trace-lua.yml
  - ./backend-policy.yml
  - ./trace-extension.yml
