apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: here-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - "*.here.pmh.so"
  rules:
    - backendRefs:
        - name: here-service
          port:
            number: 8080
