apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trace-public-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - trace.pmh.codes
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/script.js
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/replay.js
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/track
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/site/tracking-config/1
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/session-replay/record/1
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trace-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - trace.pmh.codes
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - group: ""
          kind: Service
          name: trace-service
          port: 3001
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: trace-client-service
          port: 3002
          weight: 1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: trace-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: trace-route
  oidc:
    provider:
      issuer: "https://auth.pmh.codes/application/o/trace/"
      tokenEndpoint: "http://authentik-service.authentik.svc.cluster.local:9000/application/o/token/"
    clientID: "Ux5PUQUaqqgTFvVDdHGp01HzdslYgFW7g7nWUtth"
    clientSecret:
      group: ""
      kind: "Secret"
      name: "trace-auth-secrets"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: trace-lua
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: trace-route
  lua:
    - type: Inline
      inline: |
        function envoy_on_request(request_handle)
          local path = request_handle:headers():get(":path")
          if path == "/" then
            request_handle:respond({[":status"] = "302", ["location"] = "/1"}, "")
          end
        end

        function envoy_on_response(response_handle)
          response_handle:headers():add("access-control-allow-headers", "signature")
        end
