apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trace-public-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - trace.pmh.codes
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/script.js
      backendRefs:
        - name: trace-service
          port: 3001
    - matches:
        - path:
            type: Exact
            value: /api/replay.js
      backendRefs:
        - name: trace-service
          port: 3001
    - matches:
        - path:
            type: Exact
            value: /api/track
      backendRefs:
        - name: trace-service
          port: 3001
    - matches:
        - path:
            type: Exact
            value: /api/site/tracking-config/1
      backendRefs:
        - name: trace-service
          port: 3001
    - matches:
        - path:
            type: Exact
            value: /api/session-replay/record/1
      backendRefs:
        - name: trace-service
          port: 3001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trace-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - trace.pmh.codes
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: trace-service
          port: 3001
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: trace-client-service
          port: 3002
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: trace-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: trace-route
  extAuth:
    http:
      backendRefs:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
          port: 9000
      headersToBackend:
        - Cookie
        - X-Forwarded-Host
        - X-Forwarded-Proto
        - X-Forwarded-Uri
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: trace-lua
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: trace-route
  lua:
    - type: Inline
      inline: |
        function envoy_on_request(request_handle)
          local path = request_handle:headers():get(":path")
          if path == "/" then
            request_handle:respond({[":status"] = "302", ["location"] = "/1"}, "")
          end
        end

        function envoy_on_response(response_handle)
          response_handle:headers():add("access-control-allow-headers", "signature")
        end
