apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trace-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://trace.pmh.codes/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |-
      proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Headers: signature";
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
        return 302 /1;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: trace.pmh.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trace-client-service
            port:
              number: 3002
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: trace-service
            port:
              number: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trace-public-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: trace.pmh.codes
    http:
      paths:
      - path: /api/site/tracking-config/1
        pathType: Exact
        backend:
          service:
            name: trace-service
            port:
              number: 3001
      - path: /api/session-replay/record/1
        pathType: Exact
        backend:
          service:
            name: trace-service
            port:
              number: 3001
      - path: /api/script.js
        pathType: Exact
        backend:
          service:
            name: trace-service
            port:
              number: 3001
      - path: /api/replay.js
        pathType: Exact
        backend:
          service:
            name: trace-service
            port:
              number: 3001
      - path: /api/track
        pathType: Exact
        backend:
          service:
            name: trace-service
            port:
              number: 3001
