apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: welplan-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - welplan.pmh.codes
  rules:
    - backendRefs:
        - name: welplan-service
          port: 3000
