apiVersion: apps/v1
kind: Deployment
metadata:
  name: nameserver 
spec:
  selector:
    matchLabels:
      app: nameserver 
  template:
    metadata:
      labels:
        app: nameserver 
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_local_port_range
          value: "1024 65535"
      containers:
      - name: nameserver 
        image: ghcr.io/pmh-only/adguardhome:latest
        volumeMounts:
        - name: nameserver
          mountPath: /opt/adguardhome/work
          subPath: work
        - name: nameserver
          mountPath: /opt/adguardhome/conf
          subPath: conf
      volumes:
      - name: nameserver
        persistentVolumeClaim:
          claimName: nameserver-pvc
