apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nameserver-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - names.pmh.codes
  rules:
    - backendRefs:
        - name: nameserver
          port:
            number: 5380
