apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thepool-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - pool.pmh.codes
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: thepool-service
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: thepool-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: thepool-service
  validation:
    wellKnownCACertificates: System
    hostname: pool.pmh.codes
