apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: workflows-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - flows.pmh.codes
  rules:
    - backendRefs:
        - name: workflows-service
          port: 5678
