apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radio-route
spec:
  parentRefs:
    - name: main
      namespace: gateway
  hostnames:
    - ads.pmh.codes
  rules:
    - backendRefs:
        - name: pmhraspberry
          port: 1423
