apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radio-ingress
  namespace: radio
spec:
  ingressClassName: nginx
  rules:
    - host: ads.pmh.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pmhraspberry
                port:
                  number: 1423
