apiVersion: v1
kind: Service
metadata:
  name: pmhraspberry
  namespace: radio
spec:
  type: ExternalName
  externalName: pmhraspberry.tailscale.svc.cluster.local
  ports:
    - protocol: TCP
      port: 1423
      targetPort: 1423
