apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: pmhraspberry.taildd35b7.ts.net
  name: pmhraspberry
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - protocol: TCP
      port: 1423
      targetPort: 142
    - protocol: TCP
      port: 8080
      targetPort: 8080
