apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: pmhraspberry.taildd35b7.ts.net
  name: pmhraspberry
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: pmhwindows.taildd35b7.ts.net
  name: pmhwindows
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
