apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kopia-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - backup.pmh.codes
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kopia-service
          port: 51515
          weight: 1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: kopia-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kopia-route
  oidc:
    provider:
      issuer: "https://auth.pmh.codes/application/o/kopia/"
      tokenEndpoint: "http://authentik-service.authentik.svc.cluster.local:9000/application/o/token/"
    clientID: "mtDShvttXj4pxfNLgTle6zhyH32rbWHGTOQ354Fk"
    clientSecret:
      group: ""
      kind: "Secret"
      name: "kopia-auth-secret"
