apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-configs
  namespace: argocd
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
    - jsonPointers:
        - /spec/externalName
      kind: Service
  project: default
  source:
    path: tailscale_configs
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
