apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terms-ingress
  namespace: terms
spec:
  ingressClassName: nginx
  rules:
  - host: terms.pmh.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terms
            port:
              number: 8080
