apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: terms-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - terms.pmh.codes
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: "gateway.envoyproxy.io"
          kind: Backend
          name: terms-service
          weight: 1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: terms-service
spec:
  endpoints:
    - fqdn:
        hostname: pmhraspberry.tailscale.svc.cluster.local
        port: 8080
