apiVersion: v1
kind: Service
metadata:
  name: terms
  namespace: terms
spec:
  type: ExternalName
  externalName:  pmhraspberry.tailscale.svc.cluster.local
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
